services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/E-commerce
      - JWT_SECRET=supersecretkey12345
      - PAYPAL_CLIENT_ID=123
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: beautysevicesecommerce-mongo-1
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: